scenes:
  "MainDev":
    "Video Capture Device 2":
      rotation: 90
      width: 500
      crop_left: 0
      crop_right: 0
      crop_top: 0
      crop_bottom: 0
      position_x: 130
      position_y: 130
